### ISSUE TITLE
Site Structure Primer

### ISSUE THREAD

**Issue by mypetbirdrules** [mypetbirdrules/tentacles#7]
The structure of the site is currently too complicated. The planned design of the site is as follows.

The site will have 3 pages -
- Home - the default index page will contain high-rated videos/images
- Upload - the user upload page holding a simple form for metadata input
- Search - the most useful and important page (queries the content database directly with GET requests)

The site will include a simple star-based rating system, and every video will have metadata attributes (title, description, category, resolution, date added, and unique video ID based on sha256 hash).

The site's simple design and minimal reliance on bloated web frameworks will make the server-side and client-side loads much lighter. Each video will be approved manually on upload by approved site administrators and moderators.

**Comment by fuckbunny** [comment]
Should we avoid the upload for now and add it later on, to avoid the hassle of it as of now?
